# fix this relative to include/
# or use absolute path to the GRASS source code
MODULE_TOPDIR = /usr/local/grass-6.4.2

LIBES = $(GISLIB)
DEPENDENCIES = $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

