CXX = mpicc
CXXFLAGS = -g -O2
INC = -I /usr/include
LIB =
BINARY = mserver
OBJECTS = mserver.o

all: $(BINARY)

$(BINARY): $(OBJECTS)
	$(CXX) -o $(BINARY) $(OBJECTS) $(LIB)

%.o: %.c
	$(CXX) $(CXXFLAGS) $(INC) -c $<

clean:
	rm -f $(BINARY) $(OBJECTS)
