
PGM = r.hata_gpu

include ../Makefile

#
# Include and lib dirs for the StdCL library
#
ARCH_INC += -I${ATISTREAMSDKROOT}/include
ARCH_LIBPATH += -L/usr/local/browndeer/lib
LIBES += out_clld.o

default: cmd

